version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_benchmark
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strongpassword
    volumes:
      - ./data:/data/db

